package vista;
import java.awt.event.KeyEvent;
import java.awt.Color;
import javax.swing.JOptionPane;
import logica.LogicaAlumno;
import modelo.Alumno;

public class FrmEdicionAlumno extends javax.swing.JFrame {

    private ImantenimientoCallback imc;
    public static boolean mantenimiento;

    /**
     * Creates new form FrmEdicionAlumno
     */
    public FrmEdicionAlumno() {
        initComponents();
    }

   public void mostrar(ImantenimientoCallback imc) {
        this.setLocationRelativeTo(null);
//se configura el listener
        this.imc = imc;

        if (!FrmMantenimientoAlumno.editar) {
            this.setName("Alta Alumno");
            this.setTitle("AltaAlumnos");
        } else {
            this.setName("Editar Alumno");
            this.setTitle("Editar Alumnos");
            this.txtDni.setEditable(false);
            this.txtDni.setBackground(Color.lightGray);
            txtDni.setText(FrmMantenimientoAlumno.dni);
            txtNombre.setText(FrmMantenimientoAlumno.nombre);
            if(FrmMantenimientoAlumno.mayor.equalsIgnoreCase("true"))
                chkMayor.setSelected(true);
        }

        this.setVisible(true);
    }

    private boolean datosObligatorios() {
        return txtDni.getText().isEmpty() || txtNombre.getText().isEmpty();
    }

    private void comprobarDatos() {
        if (datosObligatorios()) {
            btnAceptar.setEnabled(false);
        } else {
            btnAceptar.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        chkMayor = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(790, 540));
        setMinimumSize(new java.awt.Dimension(790, 540));
        setPreferredSize(new java.awt.Dimension(790, 540));
        setSize(new java.awt.Dimension(790, 540));

        jLabel1.setText("DNI");

        jLabel2.setText("Nombre");

        txtDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtKeyPressed(evt);
            }
        });

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtKeyPressed(evt);
            }
        });

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });

        chkMayor.setText("Mayor de Edad");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAceptar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDni)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chkMayor)
                                .addGap(0, 349, Short.MAX_VALUE))
                            .addComponent(txtNombre))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(chkMayor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 249, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnAceptar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
        if (!FrmMantenimientoAlumno.editar) {
            if (evt.getSource() == btnAceptar) {
                if (datosObligatorios()) {
                    JOptionPane.showMessageDialog(this,
                            "Faltan Datos Obligatorios",
                            this.getName(),
                            JOptionPane.WARNING_MESSAGE);
                    return;
                }
                try {

                    Alumno a = new Alumno();
                    a.setDni(txtDni.getText());
                    a.setNombre(txtNombre.getText());
                    a.setMayorEdad(chkMayor.isSelected());
                    LogicaAlumno.altaAlumno(a);

                    JOptionPane.showConfirmDialog(this,
                            "Alta Alumno Correcto",
                            this.getName(),
                            JOptionPane.PLAIN_MESSAGE);

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this,
                            "Alta Alumno Incorrecta",
                            this.getName(),
                            JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            mantenimiento=true;
            if (evt.getSource() == btnAceptar) {
                if (datosObligatorios()) {
                    JOptionPane.showMessageDialog(this,
                            "Faltan Datos Obligatorios",
                            this.getName(),
                            JOptionPane.WARNING_MESSAGE);
                    return;
                }
                try {

                    Alumno a = new Alumno();
                    a.setDni(txtDni.getText());
                    a.setNombre(txtNombre.getText());
                    a.setMayorEdad(chkMayor.isSelected());

                    LogicaAlumno.actualizaAlumno(a);

                    JOptionPane.showMessageDialog(this,
                            "Alumno Actualizado",
                            this.getName(),
                            JOptionPane.PLAIN_MESSAGE);

                } catch (Exception e) {
                    JOptionPane.showConfirmDialog(this,
                            "Actualizacion Incorrecta",
                            this.getName(),
                            JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        imc.alctualizaMto();

        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnActionPerformed

    private void txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (evt.getSource() == txtDni) {
                txtNombre.requestFocus();
            }else if(evt.getSource()==txtNombre){
                btnAceptar.requestFocus();
                btnAceptar.doClick();
            }else{
                btnCancelar.requestFocus();
                btnCancelar.doClick();
            }
        }
    }//GEN-LAST:event_txtKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEdicionAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEdicionAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEdicionAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEdicionAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEdicionAlumno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JCheckBox chkMayor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
