package vista;

import java.awt.event.KeyEvent;
import java.awt.Color;
import javax.swing.JOptionPane;
import logica.LogicaAlumno;
import logica.LogicaCurso;
import logica.LogicaMatricula;
import modelo.Alumno;
import modelo.Curso;
import modelo.Matricula;

public class FrmEdicionMatricula extends javax.swing.JFrame implements ImantenimientoCallback {

    private ImantenimientoCallback imc;

    /**
     * Creates new form FrmEdicionMatricula
     */
    public FrmEdicionMatricula() {
        initComponents();
    }

    public void mostrar(ImantenimientoCallback imc) {
        this.setLocationRelativeTo(null);
//se configura el listener
        this.imc = imc;

        this.setName("Alta Matricula");
        this.setTitle("Alta Matricula");
        txtNombreCurso.setEditable(false);
        txtNombreCurso.setBackground(Color.lightGray);
        txtNomAlumno.setEditable(false);
        txtNomAlumno.setBackground(Color.lightGray);
        this.setVisible(true);
    }

    private boolean datosObligatorios() {
        return txtDni.getText().isEmpty() || txtId.getText().isEmpty();
    }

    private void comprobarDatos() {
        if (datosObligatorios()) {
            btnAceptar.setEnabled(false);
        } else {
            btnAceptar.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtDni = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnBuscarCurso = new javax.swing.JButton();
        txtNombreCurso = new javax.swing.JTextField();
        btnBuscarProfesor = new javax.swing.JButton();
        txtNomAlumno = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(790, 540));
        setMinimumSize(new java.awt.Dimension(790, 540));
        setPreferredSize(new java.awt.Dimension(790, 540));
        setSize(new java.awt.Dimension(790, 540));

        jLabel1.setText("Id. Curso");

        jLabel3.setText("DNI Alumno");

        txtId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdFocusLost(evt);
            }
        });
        txtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtKeyPressed(evt);
            }
        });

        txtDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtKeyPressed(evt);
            }
        });

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnBuscarCurso.setText(". . .");
        btnBuscarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnBuscarProfesor.setText(". . . ");
        btnBuscarProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        txtNomAlumno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNomAlumnoFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(33, 33, 33))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDni, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtId)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtNombreCurso)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 217, Short.MAX_VALUE)
                        .addComponent(btnAceptar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtNomAlumno)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarCurso)
                    .addComponent(txtNombreCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarProfesor)
                    .addComponent(txtNomAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnAceptar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        if (datosObligatorios()) {
            JOptionPane.showMessageDialog(this,
                    "Faltan Datos Obligatorios",
                    this.getName(),
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {

            Matricula m = new Matricula();
            m.setIdCurso(Integer.parseInt(txtId.getText()));
            m.setDniAlumno(txtDni.getText());

            LogicaMatricula.altaMatricula(m);

            JOptionPane.showConfirmDialog(this,
                    "Alta Matricula Correcta",
                    this.getName(),
                    JOptionPane.PLAIN_MESSAGE);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Alta Matricula Incorrecta",
                    this.getName(),
                    JOptionPane.ERROR_MESSAGE);
        }
        imc.alctualizaMto();
        btnAceptar.setEnabled(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if (evt.getSource() == btnBuscarCurso) {
            FrmEdicionCurso.mantenimiento = true;
            FrmMantenimientoCurso frameMC = new FrmMantenimientoCurso();
            frameMC.setSize(790, 540);
            frameMC.setVisible(false);
            frameMC.mostrar(this);
        } else {
            FrmEdicionCurso.mantenimiento = true;
            FrmMantenimientoAlumno frameMP = new FrmMantenimientoAlumno();
            frameMP.setSize(790, 540);
            frameMP.setVisible(false);
            frameMP.mostrar(this);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    public void getCurso(Curso c) throws Exception {
        c.setId(Integer.parseInt(txtId.getText()));
        LogicaCurso.getCurso(c);
        txtNombreCurso.setText(c.getTitulo());
    }

    public void getAlumno(Alumno a) throws Exception {
        a.setDni(txtDni.getText());
        LogicaAlumno.getAlumno(a);
        txtNomAlumno.setText(a.getNombre());
    }

    private void txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (evt.getSource() == txtId) {
                Curso c = new Curso();
                try {
                    getCurso(c);
                    txtDni.requestFocus();
                } catch (Exception e) {
                    e.getMessage();
                }
            } else if (evt.getSource() == txtDni) {
                try {
                    Alumno a = new Alumno();
                    getAlumno(a);
                    btnAceptar.requestFocus();
                    btnAceptar.doClick();
                } catch (Exception e) {
                    e.getMessage();
                }
            } else {
                btnCancelar.requestFocus();
                btnCancelar.doClick();
            }
        }
    }//GEN-LAST:event_txtKeyPressed

    private void txtIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdFocusLost
        Curso c = new Curso();
        try {
            getCurso(c);
            txtDni.requestFocus();
        } catch (Exception e) {
            e.getMessage();
        }
    }//GEN-LAST:event_txtIdFocusLost

    private void txtNomAlumnoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomAlumnoFocusLost
        try {
            Alumno a = new Alumno();
            getAlumno(a);
            btnAceptar.requestFocus();
            btnAceptar.doClick();
        } catch (Exception e) {
            e.getMessage();
        }
    }//GEN-LAST:event_txtNomAlumnoFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEdicionMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEdicionMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEdicionMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEdicionMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEdicionMatricula().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnBuscarCurso;
    private javax.swing.JButton btnBuscarProfesor;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNomAlumno;
    private javax.swing.JTextField txtNombreCurso;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actualizarMatricula() {

        if (FrmMantenimientoCurso.mToCurso) {
            txtId.setText(Integer.toString(FrmMantenimientoCurso.id));
            txtNombreCurso.setText(FrmMantenimientoCurso.nombre);
            FrmMantenimientoCurso.mToCurso = false;
        }
        if (FrmMantenimientoAlumno.mToAlumno) {
            txtDni.setText(FrmMantenimientoAlumno.dni);
            txtNomAlumno.setText(FrmMantenimientoAlumno.nombre);
            FrmMantenimientoAlumno.mToAlumno = false;
        }
        FrmEdicionCurso.mantenimiento = false;
    }
}
