package vista;

import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import logica.LogicaAlumno;
import modelo.Alumno;

public class FrmMantenimientoAlumno extends javax.swing.JFrame implements ImantenimientoCallback {

    private ImantenimientoCallback imc;
    public static boolean editar, mToAlumno;
    public static String dni;
    public static String nombre;
    public static String mayor;
    public static String dniBuscar;
    public static String nombreBuscar;
    private DefaultTableModel modelo;
    String[] titulos = {"DNI", "Nombre", "Mayor de Edad"};

    /**
     * Creates new form FrmMantenimientoAlumno
     */
    public FrmMantenimientoAlumno() {
        initComponents();
        modelo = new DefaultTableModel(null, titulos) {
            @Override
            public boolean isCellEditable(int filas, int columnas) {
                return false;
            }
        };
        tblListado.setModel(modelo);
    }

    public void mostrar(ImantenimientoCallback imc) {

        //se configura el listener
        this.imc = imc;
                    txtDni.setText("");
            txtNombre.setText("");
        if (FrmEdicionCurso.mantenimiento) {
            this.setTitle("Buscar Alumnos");
            btnAlta.setVisible(false);
            btnBaja.setVisible(false);
            btnEditar.setVisible(false);
            btnAceptar.setVisible(true);
            btnAceptar.setEnabled(false);
        } else {
            this.setTitle("Mantenimiento Alumnos");
            btnBaja.setEnabled(false);
            btnEditar.setEnabled(false);
            btnAceptar.setVisible(false);
        }
        
        this.setLocationRelativeTo(null);
        btnBaja.setEnabled(false);
        btnEditar.setEnabled(false);
        txtDni.setText("");
        txtNombre.setText("");
        this.setVisible(true);
        TableColumnModel columnModel = tblListado.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(100);
        columnModel.getColumn(1).setPreferredWidth(200);
        columnModel.getColumn(2).setPreferredWidth(200);
        tblListado.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblListado.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tblListado.getTableHeader().setReorderingAllowed(false);

        List<Alumno> tAlumnos = new ArrayList<>();
        try {
            LogicaAlumno.listadoAlumnos(tAlumnos);
            for (Alumno a : tAlumnos) {
                modelo.addRow(new String[]{a.getDni(), a.getNombre(), Boolean.toString(a.isMayorEdad())});
            }
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(this,
                    "Error listado Alumnos",
                    this.getName(),
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contextual = new javax.swing.JPopupMenu();
        anyadir = new javax.swing.JMenuItem();
        baja = new javax.swing.JMenuItem();
        edit = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListado = new javax.swing.JTable();
        btnAlta = new javax.swing.JButton();
        btnBaja = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();

        anyadir.setText("Alta");
        anyadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anyadirActionPerformed(evt);
            }
        });
        contextual.add(anyadir);

        baja.setText("Baja");
        baja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bajaActionPerformed(evt);
            }
        });
        contextual.add(baja);

        edit.setText("Editar");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        contextual.add(edit);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(790, 540));
        setMinimumSize(new java.awt.Dimension(790, 540));
        setSize(new java.awt.Dimension(790, 540));

        jLabel1.setText("DNI");

        jLabel2.setText("Nombre");

        txtDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtKeyPressed(evt);
            }
        });

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtKeyPressed(evt);
            }
        });

        tblListado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblListado.setComponentPopupMenu(contextual);
        tblListado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblListadoMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblListado);

        btnAlta.setText("Alta");
        btnAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaActionPerformed(evt);
            }
        });

        btnBaja.setText("Baja");
        btnBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        btnLimpiar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtKeyPressed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        btnBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtKeyPressed(evt);
            }
        });

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAlta)
                        .addGap(18, 18, 18)
                        .addComponent(btnBaja)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAceptar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtDni)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimpiar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNombre)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscar))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 19, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscar)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlta)
                    .addComponent(btnBaja)
                    .addComponent(btnEditar)
                    .addComponent(btnCancelar)
                    .addComponent(btnAceptar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaActionPerformed
        if (tblListado.getSelectedRows().length < 0) {
            JOptionPane.showMessageDialog(this,
                    "No se ha seleccionado ninguna fila",
                    this.getName(),
                    JOptionPane.ERROR_MESSAGE);
            this.setVisible(false);
            this.getRootPane().getContentPane().remove(this);
        } else {
            btnEditar.setEnabled(true);
        }
        if (evt.getSource() == btnAlta) {
            frameAnyadir();
            btnAlta.setEnabled(true);
        } else if (evt.getSource() == btnEditar) {
            frameEditar();
            btnEditar.setEnabled(true);
        } else if (evt.getSource() == btnBaja) {
            if (tblListado.getSelectedRows().length < 0) {
                JOptionPane.showMessageDialog(this,
                        "No se ha seleccionado ninguna fila",
                        this.getName(),
                        JOptionPane.ERROR_MESSAGE);
                this.setVisible(false);
                this.getRootPane().getContentPane().remove(this);
            } else {
                frameBaja();

            }
        }
    }//GEN-LAST:event_btnAltaActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if (evt.getSource() == btnLimpiar) {
            txtDni.setText("");
            txtNombre.setText("");
        } else {
            buscar();
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tblListadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListadoMousePressed
        comprobarDatos();
    }//GEN-LAST:event_tblListadoMousePressed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void tblListadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListadoMouseClicked
        tblListado.isEditing();
    }//GEN-LAST:event_tblListadoMouseClicked

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        frameEditar();
        comprobarDatos();
    }//GEN-LAST:event_editActionPerformed

    private void anyadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anyadirActionPerformed
        frameAnyadir();
        comprobarDatos();
    }//GEN-LAST:event_anyadirActionPerformed

    private void bajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bajaActionPerformed
        frameBaja();
        comprobarDatos();
    }//GEN-LAST:event_bajaActionPerformed

    private void txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (FrmEdicionCurso.mantenimiento) {
                if (evt.getSource() == txtDni) {
                    txtNombre.requestFocus();
                } else if (evt.getSource() == txtNombre) {
                    btnLimpiar.requestFocus();
                    btnLimpiar.doClick();
                } else if (evt.getSource() == btnLimpiar) {
                    btnBuscar.requestFocus();
                } else {
                    btnCancelar.requestFocus();
                    btnCancelar.doClick();
                }
            } else {
                if (evt.getSource() == txtDni) {
                    txtNombre.requestFocus();
                } else if (evt.getSource() == txtNombre) {
                    btnLimpiar.requestFocus();
                    btnLimpiar.doClick();
                } else if (evt.getSource() == btnLimpiar) {
                    btnBuscar.requestFocus();
                } else {
                    btnCancelar.requestFocus();
                    btnCancelar.doClick();
                }
            }
        }
    }//GEN-LAST:event_txtKeyPressed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        dni = (String) modelo.getValueAt(tblListado.getSelectedRow(), 0);
        nombre = (String) modelo.getValueAt(tblListado.getSelectedRow(), 1);
        mToAlumno = true;
        FrmEdicionAlumno.mantenimiento=false;
        imc.actualizarMatricula();
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnAceptarActionPerformed

    public boolean isCellEditable(int rowIndex, int colIndex) {
        return false;
    }

    private void comprobarDatos() {
        if (tblListado.getSelectedRows().length > 0) {
            btnAlta.setEnabled(false);
            btnEditar.setEnabled(true);
            btnBaja.setEnabled(true);
            btnAceptar.setEnabled(true);
        } else {
            btnAlta.setEnabled(true);
            btnEditar.setEnabled(false);
            btnBaja.setEnabled(false);
            btnAceptar.setEnabled(false);
        }
    }

    public void frameAnyadir() {
        btnAlta.setEnabled(false);
        editar = false;
        FrmEdicionAlumno panelPM = new FrmEdicionAlumno();
        panelPM.setSize(790, 540);
        panelPM.setVisible(false);
        panelPM.mostrar(this);
    }

    public void frameEditar() {
        btnEditar.setEnabled(false);
        editar = true;
        dni = (String) modelo.getValueAt(tblListado.getSelectedRow(), 0);
        nombre = (String) modelo.getValueAt(tblListado.getSelectedRow(), 1);
        mayor = (String) modelo.getValueAt(tblListado.getSelectedRow(), 2);
        FrmEdicionAlumno panelPM = new FrmEdicionAlumno();
        panelPM.setSize(790, 540);
        panelPM.setVisible(false);
        panelPM.mostrar(this);
    }

    private void frameBaja() {
        if (JOptionPane.showConfirmDialog(this,
                "¿Realmente desea borrar el alumno seleccionado?",
                this.getName(),
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE) == 0) {

            try {
                Alumno a = new Alumno();

                a.setDni((String) modelo.getValueAt(tblListado.getSelectedRow(), 0));

                LogicaAlumno.bajaAlumno(a);
                JOptionPane.showMessageDialog(this,
                        "Baja Alumno Correcta",
                        this.getName(),
                        JOptionPane.PLAIN_MESSAGE);
                modelo.removeRow(tblListado.getSelectedRow());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,
                        "Baja Alumno Inorrecta",
                        this.getName(),
                        JOptionPane.ERROR_MESSAGE);
            }
            comprobarDatos();
        }
    }

    private void buscar() {
        try {
            dniBuscar = txtDni.getText();
            nombreBuscar = txtNombre.getText();
            modelo.setRowCount(0);
            tblListado.setModel(modelo);
            List<Alumno> tAlumnos = new ArrayList<>();
            LogicaAlumno.buscar(tAlumnos);
            for (Alumno a : tAlumnos) {
                modelo.addRow(new String[]{a.getDni(), a.getNombre(), Boolean.toString(a.isMayorEdad())});
            }
            txtDni.setText("");
            txtNombre.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error busqueda Alumnos",
                    this.getName(),
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMantenimientoAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMantenimientoAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMantenimientoAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMantenimientoAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMantenimientoAlumno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem anyadir;
    private javax.swing.JMenuItem baja;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAlta;
    private javax.swing.JButton btnBaja;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JPopupMenu contextual;
    private javax.swing.JMenuItem edit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblListado;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

    @Override
    public void alctualizaMto() {
        txtDni.setText("");
        txtNombre.setText("");
        buscar();
    }
}
