package vista;

import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import logica.ConexionBD;


public class T12p03_GUI extends javax.swing.JFrame implements ImantenimientoCallback{

    /**
     * Creates new form T12p01_GUI
     */
    public T12p03_GUI() {
        initComponents();
        inits();
        this.setTitle("Gestion Matriculas");
    }

    private void inits() {
        this.setLocationRelativeTo(null);
        UIManager.put("OptionPane.messageFont", new Font("Tahoma", Font.PLAIN, 18));
        UIManager.put("OptionPane.buttonFont", new Font("Tahoma", Font.PLAIN, 18));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        menuPrincipal = new javax.swing.JMenu();
        menuPrincipalSalir = new javax.swing.JMenuItem();
        menuMantenimiento = new javax.swing.JMenu();
        menuMantenimientoProfesor = new javax.swing.JMenuItem();
        menuMantenimientoCurso = new javax.swing.JMenuItem();
        menuMantenimientoAlumno = new javax.swing.JMenuItem();
        menuMantenimientoMatricula = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("T12p03");
        setMinimumSize(new java.awt.Dimension(800, 600));
        setName("PracticaT12p01"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        menuPrincipal.setText("Principal");

        menuPrincipalSalir.setText("Salir");
        menuPrincipalSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPrincipalSalirActionPerformed(evt);
            }
        });
        menuPrincipal.add(menuPrincipalSalir);

        menuBar.add(menuPrincipal);

        menuMantenimiento.setText("Mantenimiento");

        menuMantenimientoProfesor.setText("Profesores");
        menuMantenimientoProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });
        menuMantenimiento.add(menuMantenimientoProfesor);

        menuMantenimientoCurso.setText("Cursos");
        menuMantenimientoCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });
        menuMantenimiento.add(menuMantenimientoCurso);

        menuMantenimientoAlumno.setText("Alumnos");
        menuMantenimientoAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });
        menuMantenimiento.add(menuMantenimientoAlumno);

        menuMantenimientoMatricula.setText("Matriculas");
        menuMantenimientoMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });
        menuMantenimiento.add(menuMantenimientoMatricula);

        menuBar.add(menuMantenimiento);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuPrincipalSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPrincipalSalirActionPerformed
        int op = JOptionPane.showConfirmDialog(this,
                "¿Estas seguro?",
                this.getName(),
                JOptionPane.YES_NO_OPTION);
        switch (op) {
            case JOptionPane.YES_OPTION:

                /* CERRAR CONEXIÓN BD *************************************/
                try {
                    System.out.println("Cerrando conexión BD...");
                    ConexionBD.cerrarConexion();
                    System.out.println("Conexión cerrada correctamente.");
                } catch (Exception e) {
                    System.out.println("Error!!\n" + e.getMessage());
                    JOptionPane.showConfirmDialog(this,
                            "ERROR",
                            this.getName(),
                            JOptionPane.ERROR_MESSAGE);
                }
                /* ********************************************************/
                this.setVisible(false);
                this.dispose();
                break;
        }
    }//GEN-LAST:event_menuPrincipalSalirActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        /* ABRIR CONEXIÓN BD **************************************************/
        try {
            System.out.println("Abriendo conexión BD...");
            ConexionBD.abrirConexion();
            System.out.println("Conexión abierta correctamente.");
        } catch (Exception e) {
            System.out.println("Error!!\n" + e.getMessage());
            JOptionPane.showConfirmDialog(this,
                    "ERROR",
                    this.getName(),
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_formWindowOpened

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        this.getContentPane().removeAll();
        if (evt.getSource() == menuMantenimientoProfesor) {
            FrmMantenimientoProfesores frameMP=new FrmMantenimientoProfesores();
            frameMP.setSize(790,540);
            frameMP.setVisible(false);
            frameMP.mostrar();
        } else if (evt.getSource() == menuMantenimientoAlumno) {
            FrmMantenimientoAlumno frameMA = new FrmMantenimientoAlumno();
            frameMA.setSize(790,540);
            frameMA.setVisible(false);
            frameMA.mostrar(this);
        }else if (evt.getSource() == menuMantenimientoCurso) {
            FrmMantenimientoCurso frameMC = new FrmMantenimientoCurso();
            frameMC.setSize(790,540);
            frameMC.setVisible(false);
            frameMC.mostrar();
        } else {
            FrmMantenimientoMatricula frameMM = new FrmMantenimientoMatricula();
            frameMM.setSize(790,540);
            frameMM.setVisible(false);
            frameMM.mostrar();
        
        }
    
    }//GEN-LAST:event_menuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(T12p03_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(T12p03_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(T12p03_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(T12p03_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new T12p03_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuMantenimiento;
    private javax.swing.JMenuItem menuMantenimientoAlumno;
    private javax.swing.JMenuItem menuMantenimientoCurso;
    private javax.swing.JMenuItem menuMantenimientoMatricula;
    private javax.swing.JMenuItem menuMantenimientoProfesor;
    private javax.swing.JMenu menuPrincipal;
    private javax.swing.JMenuItem menuPrincipalSalir;
    // End of variables declaration//GEN-END:variables


}
